# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Woa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Woa
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya', '~> 15.0'

  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestore'

  pod 'SwiftGen'

end
