# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Woa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Woa
  pod 'SwiftLint'
  pod 'SnapKit'
  pod 'Moya'

  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestore'

end
